#!/bin/sh
export GIT_HOME=$(cd `dirname $0`; pwd)
cd $GIT_HOME
export PROGRAM_SOURCE=$GIT_HOME/cloud-repo
if [ ! -d "$PROGRAM_SOURCE" ]; then
   git clone https://github.com/xugc/cloud-repo.git
fi
cd $PROGRAM_SOURCE
git pull
export profile=$1
if [ -z "${profile}" ]; then
   profile=dev
fi
echo "current profile is : ${profile}."
mvn clean package -Dmaven.test.skip=true -P ${profile}